# Usa uma imagem oficial do Python
FROM python:latest

# Define a pasta de trabalho dentro do container
WORKDIR /app

# Define UTF-8
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONIOENCODING=UTF-8
ENV PYTHONUTF8=1

RUN pip install Flask && pip install bcrypt && pip install mysql-connector-python
# Copia o código da aplicação
COPY . .

# Expõe a porta da aplicação
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "app.py"]


